# Generated by Django 4.1.6 on 2023-02-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='group',
            field=models.ManyToManyField(to='splitwise.group'),
        ),
    ]
