# Generated by Django 4.1.6 on 2023-02-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0002_users_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('default_current', models.CharField(choices=[('INR', 'INDIA'), ('EURO', 'GERMANY'), ('DLR', 'DOLLAR')], default='INR', max_length=5)),
                ('group', models.ManyToManyField(to='splitwise.group')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitwise.user'),
        ),
        migrations.AlterField(
            model_name='split',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitwise.user'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
