# Generated by Django 4.1.6 on 2023-02-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='split',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Split',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
