# Generated by Django 4.1.6 on 2023-02-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0008_activity_group_split_user_delete_sandwich_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(to='splitwise.user'),
        ),
    ]
